language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - AWS_REGION=ap-southeast-1
    - PGPORT=5433
    - CC_TEST_REPORTER_ID=0d3f29fe1c737e27dcc5b679ddf2af93ddcbe3cf42f4b78cfe3324ba9270b545
    - CODECOV_TOKEN="2aaec902-1e35-4664-aa6c-6f1ace7bb77d"
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - gem install bundler
before_script:
  - psql -c 'create database twilreapi_test;' -U travis
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
