language: ruby
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database twilreapi_test;' -U postgres
- psql -U postgres -c "create extension pgcrypto"
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "IVDHS0/sKcE+kDLXT/AmJLugLiQBbN5NUdwmGG7rMlB6HeHiCDLdKsIuP6A/oW3X+bCgEMgA1Auj6kn+aBHH8Wn12zExki5ADX8KhuuPAuBfS6Uzcuy6rzOyFYCUsiki+MHMYrSi8GXKLO/Q8fs+3KtAjpENO2NV5ca5ZPKv9PfSy8NNhVyKGb6I17ELb4KZcwuKlLddzTJMr6DrxVU7H01Gmc5v5qNIjLfYe8vSL58/kLXCcIyWe3ElMDCrFyePsE27hl5JNmwWutAhLoB+oKF3CQBXGlhP6IfF6MqBgq6d6xmP6PjEDLB9j6MKItuiTm6pryXXmf+jBzp1HQclgpN37IWUi4wVEQybW4r5GwbheSZjextHFZ6bNGJnnBO1ybZfhEIjpGkNn6zonSPl4nsa+EMw7t1JIbqIt9PI+rR2xkENMwglXbJnxnHuZZf9fw4HQSJjbBX5UU7ofPR5EjkWlIQKFm7PipEFuSjyY6V1dW2iZ8+llWLGWzPFU8DPZBI3W51SZP4Qv07BFSvUxWbTokEThHfQ6MDFIiPbxy4zYAusuLU3zLO8G/Cddz/jlhII2oHvpYzkPq7b/qTGygTsJEb+tkgwEsl1bxTibK/b2uMQQdlkzaw4pQ2Ln4QDP96dRgBu4tGFz13oURuvIIVkIf5FXY2W5m5uw0m/p3w="
  secret-access-key:
    secure: "7HXP2oawRVQ96oZ5WOyzk99ea23LyGfySwKlf5Emo6xJFdA8irXSOtmPJE6QOVyFpynv/U7EV0tR2uu3ZCnf8dXA9EmSsNAratXe9jCsMV0nKnA1EouZ0+syrKN69/5TkIyKt2yy25P4gnwF3wrTGBBQfmA1MY7SIy01Zuu4yYpvuYTNE3koRx5/BE0I8sMqdKO0QEvRPKu9QgYURkjynKVFr39yo+znq6R1ha8KxRdJMsPrjbSadGj2x+j/4MN2UZ6ULeQlydhMq8hTfo4aMn76ACkQHrwAXcVZfwf2tatxvdvf0oGEGVgehpe6APdr3ILQOlQipBDdYsxchUc4dNt/Q8odMUypWmisOYPE6auP5UY6LMl5c1NH38pJU8CRUSmiY8uWzrGMUFnDZqfJSzaLPObRg7t8TunszkKxvKNUGHyYbL9YBJ+ANJXi/nJw8GQCwtOWIC02t9OVcdSjUZB52iwVOPGLlmSaZyIuxec/VYJc/jkvffAsymqwgN4AGZyg3F+ZIs00oMTZTj2WMs0Dp50xlyQlFIIvSkzr9KHkQmhOEgqYqbFk7dLJ/mIc6IJ5vF/pDc/DjRggi531dQDqAkx2dIcEzkazhsg9PAbXKJ9Q2uXGDy0cAJZOA5VhPNZQ+W5PF07K6WjJBfH2tMBrgAN0w8BOZwBRLdHxPOE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "IVDHS0/sKcE+kDLXT/AmJLugLiQBbN5NUdwmGG7rMlB6HeHiCDLdKsIuP6A/oW3X+bCgEMgA1Auj6kn+aBHH8Wn12zExki5ADX8KhuuPAuBfS6Uzcuy6rzOyFYCUsiki+MHMYrSi8GXKLO/Q8fs+3KtAjpENO2NV5ca5ZPKv9PfSy8NNhVyKGb6I17ELb4KZcwuKlLddzTJMr6DrxVU7H01Gmc5v5qNIjLfYe8vSL58/kLXCcIyWe3ElMDCrFyePsE27hl5JNmwWutAhLoB+oKF3CQBXGlhP6IfF6MqBgq6d6xmP6PjEDLB9j6MKItuiTm6pryXXmf+jBzp1HQclgpN37IWUi4wVEQybW4r5GwbheSZjextHFZ6bNGJnnBO1ybZfhEIjpGkNn6zonSPl4nsa+EMw7t1JIbqIt9PI+rR2xkENMwglXbJnxnHuZZf9fw4HQSJjbBX5UU7ofPR5EjkWlIQKFm7PipEFuSjyY6V1dW2iZ8+llWLGWzPFU8DPZBI3W51SZP4Qv07BFSvUxWbTokEThHfQ6MDFIiPbxy4zYAusuLU3zLO8G/Cddz/jlhII2oHvpYzkPq7b/qTGygTsJEb+tkgwEsl1bxTibK/b2uMQQdlkzaw4pQ2Ln4QDP96dRgBu4tGFz13oURuvIIVkIf5FXY2W5m5uw0m/p3w="
  secret-access-key:
    secure: "7HXP2oawRVQ96oZ5WOyzk99ea23LyGfySwKlf5Emo6xJFdA8irXSOtmPJE6QOVyFpynv/U7EV0tR2uu3ZCnf8dXA9EmSsNAratXe9jCsMV0nKnA1EouZ0+syrKN69/5TkIyKt2yy25P4gnwF3wrTGBBQfmA1MY7SIy01Zuu4yYpvuYTNE3koRx5/BE0I8sMqdKO0QEvRPKu9QgYURkjynKVFr39yo+znq6R1ha8KxRdJMsPrjbSadGj2x+j/4MN2UZ6ULeQlydhMq8hTfo4aMn76ACkQHrwAXcVZfwf2tatxvdvf0oGEGVgehpe6APdr3ILQOlQipBDdYsxchUc4dNt/Q8odMUypWmisOYPE6auP5UY6LMl5c1NH38pJU8CRUSmiY8uWzrGMUFnDZqfJSzaLPObRg7t8TunszkKxvKNUGHyYbL9YBJ+ANJXi/nJw8GQCwtOWIC02t9OVcdSjUZB52iwVOPGLlmSaZyIuxec/VYJc/jkvffAsymqwgN4AGZyg3F+ZIs00oMTZTj2WMs0Dp50xlyQlFIIvSkzr9KHkQmhOEgqYqbFk7dLJ/mIc6IJ5vF/pDc/DjRggi531dQDqAkx2dIcEzkazhsg9PAbXKJ9Q2uXGDy0cAJZOA5VhPNZQ+W5PF07K6WjJBfH2tMBrgAN0w8BOZwBRLdHxPOE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-mt-worker
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "IVDHS0/sKcE+kDLXT/AmJLugLiQBbN5NUdwmGG7rMlB6HeHiCDLdKsIuP6A/oW3X+bCgEMgA1Auj6kn+aBHH8Wn12zExki5ADX8KhuuPAuBfS6Uzcuy6rzOyFYCUsiki+MHMYrSi8GXKLO/Q8fs+3KtAjpENO2NV5ca5ZPKv9PfSy8NNhVyKGb6I17ELb4KZcwuKlLddzTJMr6DrxVU7H01Gmc5v5qNIjLfYe8vSL58/kLXCcIyWe3ElMDCrFyePsE27hl5JNmwWutAhLoB+oKF3CQBXGlhP6IfF6MqBgq6d6xmP6PjEDLB9j6MKItuiTm6pryXXmf+jBzp1HQclgpN37IWUi4wVEQybW4r5GwbheSZjextHFZ6bNGJnnBO1ybZfhEIjpGkNn6zonSPl4nsa+EMw7t1JIbqIt9PI+rR2xkENMwglXbJnxnHuZZf9fw4HQSJjbBX5UU7ofPR5EjkWlIQKFm7PipEFuSjyY6V1dW2iZ8+llWLGWzPFU8DPZBI3W51SZP4Qv07BFSvUxWbTokEThHfQ6MDFIiPbxy4zYAusuLU3zLO8G/Cddz/jlhII2oHvpYzkPq7b/qTGygTsJEb+tkgwEsl1bxTibK/b2uMQQdlkzaw4pQ2Ln4QDP96dRgBu4tGFz13oURuvIIVkIf5FXY2W5m5uw0m/p3w="
  secret-access-key:
    secure: "7HXP2oawRVQ96oZ5WOyzk99ea23LyGfySwKlf5Emo6xJFdA8irXSOtmPJE6QOVyFpynv/U7EV0tR2uu3ZCnf8dXA9EmSsNAratXe9jCsMV0nKnA1EouZ0+syrKN69/5TkIyKt2yy25P4gnwF3wrTGBBQfmA1MY7SIy01Zuu4yYpvuYTNE3koRx5/BE0I8sMqdKO0QEvRPKu9QgYURkjynKVFr39yo+znq6R1ha8KxRdJMsPrjbSadGj2x+j/4MN2UZ6ULeQlydhMq8hTfo4aMn76ACkQHrwAXcVZfwf2tatxvdvf0oGEGVgehpe6APdr3ILQOlQipBDdYsxchUc4dNt/Q8odMUypWmisOYPE6auP5UY6LMl5c1NH38pJU8CRUSmiY8uWzrGMUFnDZqfJSzaLPObRg7t8TunszkKxvKNUGHyYbL9YBJ+ANJXi/nJw8GQCwtOWIC02t9OVcdSjUZB52iwVOPGLlmSaZyIuxec/VYJc/jkvffAsymqwgN4AGZyg3F+ZIs00oMTZTj2WMs0Dp50xlyQlFIIvSkzr9KHkQmhOEgqYqbFk7dLJ/mIc6IJ5vF/pDc/DjRggi531dQDqAkx2dIcEzkazhsg9PAbXKJ9Q2uXGDy0cAJZOA5VhPNZQ+W5PF07K6WjJBfH2tMBrgAN0w8BOZwBRLdHxPOE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-cdr-processor
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
