language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - AWS_REGION=ap-southeast-1
  - PGPORT=5433
  - CC_TEST_REPORTER_ID="ac1f9c247edec2b4c9779f6154f5ceba88956641d6073e109661b1554771de6a"
  - secure: "JE3OUOb5/ujeMI/+/WffttXDN2H4cLCj2Mbru5IhQ5pDTMCXMGGiH0qglPc2fEJ2ByocWZyQojg+hJZT5+Q2iCVUemtdMq3/ZBiFhHh4AtWaQanrxtYYjB19J1c/+VXuP6Duc86J85C9MUVaeoalu0XIBaNumahIQ0R2NJMKm7BRlMBLheBzqZWVl0jQPlK4lgEzg4WEzvjGPLJe9CdnPL90RSmCEhn1dLl/fXpWuhVwoOTukrpiCmfrTMX1BA5mxoppsWsIxBuc9C2YvfdKa83LU8fn4ZefhgnNGGU/KvBOZQ0LrqTaYgOq5TkmunoNxBegqsYiGsoSdkviPzb1OXsPxz4nwuV4JYgee+OH3OEpPDBfqnfn1B+DlLmKF5E6VBXrtc0Jv4f5KlC1TUfI8uslWxiqhCQvG9j1PSte+TpljBGaptvnIlpKPfWhYdKNGZPbmB8G2sWQO2J4QNbV5+w+TqpXkQteDel9eWGeexOcy6Kv5klo5+mxCwjglHhD0RgmDo8BPtk4ZtiA16U5mO+tToKGps/qqNfnai1WFg0xYJzMNtZM4VamQxGFV/kXppQE5XjfEgRsB8y8ldG+zlkRFbFg/6Kwd2BRaLjLxmKt3zR+OvX9VVhUM4eQd+XqiuI/Q/OB0550RzJS1Oe9F5YEZDS1ofxQvWOn5O+gCFM="
before_install:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- gem install bundler
before_script:
- psql -c 'create database twilreapi_test;' -U travis
- "./cc-test-reporter before-build"
after_success:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-webserver
  bucket_name: deploy.ews1294.info
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-worker
  bucket_name: deploy.ews1294.info
  on:
    branch: master
- provider: elasticbeanstalk
  region: ap-southeast-1
  app: somleng-twilreapi
  env: somleng-twilreapi-caller-worker
  bucket_name: deploy.ews1294.info
  on:
    branch: master
