language: ruby
sudo: false
services:
  - postgresql
env:
  global:
    - START_SIMPLECOV=1
addons:
  postgresql: '9.6'
  code_climate:
    repo_token:
      secure: "ixvE5zOUySIHsUCLWjuoDqikwjW9yHERucrouHRw6TMLZHdMw2dLtHoANOJblSNvQ/RY+w1qNEX7wUgKbjoy7MfxZauNSFzoiCBejrsSyXSGtopIdUZilRyPP8OPS2f4RBlTf5pNX1iFay1UEM+o38NyOW68LTaQahJ9pUjGDsljdqQcZJSX6NxZ3HiY4shyetzeA3zlC+31GG02hd44zsvh05oRJrlT0wAa6PrzmAc0hHWWDhCCe/yN+JQyM5Ac+vFq7/uDUkrpj4dWKauZfpxk7kdU+QmtSEW+qeC65C9kCRxWqSKlqfhPs8WZjy//gQ5dk1Y7asq+fwvoBU9j90XI+31++TX8HB7Yb2U3wYleLJIE9bYIsnwFAv0gp5KuX65Zaw64xEvH6wmiDXDFYmktiFInUz4skk26zjB/7n3wCrVPD5ZbzXIzD0STb+BHwoRkMdYjfCuUmG1YpOOHZiOt8kaiE2413GuvD8C5UYoyltJzkPHAcwf2f6rqa1+trRn+1GwlppICQodgkMHE3Gv5QVy0Lm+7l+7qQ2zOvqWU2UjjYKeFR17MFgZ+xZ6bP6rkm8pl5OleT6p1fpJzclSEn5SMxM0xQgu5Uw5gtHIB82bJkzuACaecpGo0HkC/JJ9/MJ9FZspiFLGttGq1cdbCK37iw50ynB4GN05U2Y0="
before_script:
  - psql -c 'create database twilreapi_test;' -U postgres
  - psql -U postgres -c "create extension pgcrypto"
deploy:
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-web
    bucket_name: pin-somlengci
    on:
      repo: somleng/twilreapi
      branch: somleng.ews1294.info
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-worker
    bucket_name: pin-somlengci
    on:
      repo: somleng/twilreapi
      branch: somleng.ews1294.info
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-cdr-processor
    bucket_name: pin-somlengci
    on:
      repo: somleng/twilreapi
      branch: somleng.ews1294.info
after_success:
  - bundle exec codeclimate-test-reporter
