language: ruby
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database twilreapi_test;' -U postgres
- psql -U postgres -c "create extension pgcrypto"
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "iHbvdlqUIxlMC9rH3WEIc0h1ohz5+WQgrvIovRkd3As5/CiTA5QJbmlDXRdtiSfh9Mz4mBHBM5i5fJYmOHg+EUVoS7Y6xgp0atzp6I3UaxWcdZ2y/Ai4QhZnNmP5TfmMQjJ85dvBbXuJTPxYvZIBoH7PQn19sc68WNeXJw2aeVNk4nDwIPZosUzSlfMeNXKlZH8R8h80wTm5gfbtWiZfcFccO3KiGHQRHe5vdBoA89nAgiYgbivPktbtxzjQFsyTN2+AlSvvxCaoRs1MUu410FQFL83KlLxFRk4kz6FFsI1EEGrXaV/3xaw66ICpaUb6dJabFbYiqFymIFCaSV8WNAPYU5gyuUXCuEI6MfOKVtswb2plj7aRkWWt0gMIuwVFcO/EwRAvfBHlNaOhtNPxb1fr4kaSy+aK3thxkwUhem1ANTuOXUydlnwnHcLC9eLzOF76exHiIoNPGFbczSAZ6dv7FscdaU4CuqEpEA0nfOsOUfyASyQCtpjxBIIGFmAEvzvvYObWwyF2Ypgxugf22Jf7VX7OpGWKtHf8wGOjdITe+LGe9Fypx+3scme+mqn4SDFJbsgq/Si9Yc4wJBcQCegHRMu0eCENyAIBT23kcGYjYDV0r8pBDRuo3Vs+GqVmCYRYbFZQnlteSxu350rupA1sCoucUOlO84IOu0JtR5k="
  secret-access-key:
    secure: "1miVJKwHYDgaacLbaK5PpelM7n54aGFYh+Hi7mt8PulK55osFEDDlGZwB74CBVnx6R2yobc11tRPPi5PYJP5llKXi8ko4uhfa9w4UvY2UQ7OSukHZmIU5zd+im61G6jLI9KfGlpyMh1y/uNzAvDaMmaHCvtveFb72fV6b6PtVZEOyaTEL1VCb+SoJK5hP0Jk0BdVFAr4VwLBEPq951ZvT0Tv6V7GWGsSsFe489oQAznwtB22wLHr97Ie2aqLnF1sR8LS12MTIbHFLPbuXdYOtjPpDFK2gwMe3xz0pa/7reKqwGZX1lcp1Hh0MkFxsffGfuUGO2LEGkWRHtmVm28kwUiFLFmk/IHQ0MejOIYIifCFNfWoi1xYz29N9ZZWO7HYbQpSoaNCTP9IxuT7uwUNIh1hgKz4Hx6MBVw0O37UqN9xAdveUKZRQC4O9ihwqvDzu4Ps6EDmtizCQJHHIfZAaalA2t4PbX4TkBMEqMgH/xQ/kQaj8BRvyWoe8/HoBtDDm9sCQRIPgJFd5UO9d2yVsWMAld/Nq1C5oqqkcMQt3jY7sb9Tdhd/1WqD/WFgt4mY3XLUlgg3u+REjHOicwkpZkuteOWg9sPfiV/8637CrBuXE8yWsAiwci8KNA688fICFvhSTbpYNRgVpSKqx1YSX8W5GGhn9px/2Qq2iZLn/CE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-web
  bucket_name: elasticbeanstalk-ap-southeast-1-314673618878
  on:
    repo: dwilkie/twilreapi
    branch: somleng.ews1294.info

- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "iHbvdlqUIxlMC9rH3WEIc0h1ohz5+WQgrvIovRkd3As5/CiTA5QJbmlDXRdtiSfh9Mz4mBHBM5i5fJYmOHg+EUVoS7Y6xgp0atzp6I3UaxWcdZ2y/Ai4QhZnNmP5TfmMQjJ85dvBbXuJTPxYvZIBoH7PQn19sc68WNeXJw2aeVNk4nDwIPZosUzSlfMeNXKlZH8R8h80wTm5gfbtWiZfcFccO3KiGHQRHe5vdBoA89nAgiYgbivPktbtxzjQFsyTN2+AlSvvxCaoRs1MUu410FQFL83KlLxFRk4kz6FFsI1EEGrXaV/3xaw66ICpaUb6dJabFbYiqFymIFCaSV8WNAPYU5gyuUXCuEI6MfOKVtswb2plj7aRkWWt0gMIuwVFcO/EwRAvfBHlNaOhtNPxb1fr4kaSy+aK3thxkwUhem1ANTuOXUydlnwnHcLC9eLzOF76exHiIoNPGFbczSAZ6dv7FscdaU4CuqEpEA0nfOsOUfyASyQCtpjxBIIGFmAEvzvvYObWwyF2Ypgxugf22Jf7VX7OpGWKtHf8wGOjdITe+LGe9Fypx+3scme+mqn4SDFJbsgq/Si9Yc4wJBcQCegHRMu0eCENyAIBT23kcGYjYDV0r8pBDRuo3Vs+GqVmCYRYbFZQnlteSxu350rupA1sCoucUOlO84IOu0JtR5k="
  secret-access-key:
    secure: "1miVJKwHYDgaacLbaK5PpelM7n54aGFYh+Hi7mt8PulK55osFEDDlGZwB74CBVnx6R2yobc11tRPPi5PYJP5llKXi8ko4uhfa9w4UvY2UQ7OSukHZmIU5zd+im61G6jLI9KfGlpyMh1y/uNzAvDaMmaHCvtveFb72fV6b6PtVZEOyaTEL1VCb+SoJK5hP0Jk0BdVFAr4VwLBEPq951ZvT0Tv6V7GWGsSsFe489oQAznwtB22wLHr97Ie2aqLnF1sR8LS12MTIbHFLPbuXdYOtjPpDFK2gwMe3xz0pa/7reKqwGZX1lcp1Hh0MkFxsffGfuUGO2LEGkWRHtmVm28kwUiFLFmk/IHQ0MejOIYIifCFNfWoi1xYz29N9ZZWO7HYbQpSoaNCTP9IxuT7uwUNIh1hgKz4Hx6MBVw0O37UqN9xAdveUKZRQC4O9ihwqvDzu4Ps6EDmtizCQJHHIfZAaalA2t4PbX4TkBMEqMgH/xQ/kQaj8BRvyWoe8/HoBtDDm9sCQRIPgJFd5UO9d2yVsWMAld/Nq1C5oqqkcMQt3jY7sb9Tdhd/1WqD/WFgt4mY3XLUlgg3u+REjHOicwkpZkuteOWg9sPfiV/8637CrBuXE8yWsAiwci8KNA688fICFvhSTbpYNRgVpSKqx1YSX8W5GGhn9px/2Qq2iZLn/CE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-worker
  bucket_name: elasticbeanstalk-ap-southeast-1-314673618878
  on:
    repo: dwilkie/twilreapi
    branch: somleng.ews1294.info

- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "iHbvdlqUIxlMC9rH3WEIc0h1ohz5+WQgrvIovRkd3As5/CiTA5QJbmlDXRdtiSfh9Mz4mBHBM5i5fJYmOHg+EUVoS7Y6xgp0atzp6I3UaxWcdZ2y/Ai4QhZnNmP5TfmMQjJ85dvBbXuJTPxYvZIBoH7PQn19sc68WNeXJw2aeVNk4nDwIPZosUzSlfMeNXKlZH8R8h80wTm5gfbtWiZfcFccO3KiGHQRHe5vdBoA89nAgiYgbivPktbtxzjQFsyTN2+AlSvvxCaoRs1MUu410FQFL83KlLxFRk4kz6FFsI1EEGrXaV/3xaw66ICpaUb6dJabFbYiqFymIFCaSV8WNAPYU5gyuUXCuEI6MfOKVtswb2plj7aRkWWt0gMIuwVFcO/EwRAvfBHlNaOhtNPxb1fr4kaSy+aK3thxkwUhem1ANTuOXUydlnwnHcLC9eLzOF76exHiIoNPGFbczSAZ6dv7FscdaU4CuqEpEA0nfOsOUfyASyQCtpjxBIIGFmAEvzvvYObWwyF2Ypgxugf22Jf7VX7OpGWKtHf8wGOjdITe+LGe9Fypx+3scme+mqn4SDFJbsgq/Si9Yc4wJBcQCegHRMu0eCENyAIBT23kcGYjYDV0r8pBDRuo3Vs+GqVmCYRYbFZQnlteSxu350rupA1sCoucUOlO84IOu0JtR5k="
  secret-access-key:
    secure: "1miVJKwHYDgaacLbaK5PpelM7n54aGFYh+Hi7mt8PulK55osFEDDlGZwB74CBVnx6R2yobc11tRPPi5PYJP5llKXi8ko4uhfa9w4UvY2UQ7OSukHZmIU5zd+im61G6jLI9KfGlpyMh1y/uNzAvDaMmaHCvtveFb72fV6b6PtVZEOyaTEL1VCb+SoJK5hP0Jk0BdVFAr4VwLBEPq951ZvT0Tv6V7GWGsSsFe489oQAznwtB22wLHr97Ie2aqLnF1sR8LS12MTIbHFLPbuXdYOtjPpDFK2gwMe3xz0pa/7reKqwGZX1lcp1Hh0MkFxsffGfuUGO2LEGkWRHtmVm28kwUiFLFmk/IHQ0MejOIYIifCFNfWoi1xYz29N9ZZWO7HYbQpSoaNCTP9IxuT7uwUNIh1hgKz4Hx6MBVw0O37UqN9xAdveUKZRQC4O9ihwqvDzu4Ps6EDmtizCQJHHIfZAaalA2t4PbX4TkBMEqMgH/xQ/kQaj8BRvyWoe8/HoBtDDm9sCQRIPgJFd5UO9d2yVsWMAld/Nq1C5oqqkcMQt3jY7sb9Tdhd/1WqD/WFgt4mY3XLUlgg3u+REjHOicwkpZkuteOWg9sPfiV/8637CrBuXE8yWsAiwci8KNA688fICFvhSTbpYNRgVpSKqx1YSX8W5GGhn9px/2Qq2iZLn/CE="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-cdr-processor
  bucket_name: elasticbeanstalk-ap-southeast-1-314673618878
  on:
    repo: dwilkie/twilreapi
    branch: somleng.ews1294.info
