language: ruby
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database twilreapi_test;' -U postgres
- psql -U postgres -c "create extension pgcrypto"
deploy:
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "yvpjV1iG9/cC7P3+9P6z7trmBPDXFhQoqhblkzcXqDUwfzEZB9T6CE0EP0L/kUdlJMppzKue5nGBQ7w3YVuSyCmopdr5UtufYprG6VpQd8QzJMMY9H9U7LSpYhmxRxolTOFgmB3i7dnyY05IYHdBcQpcFBTVuSZunxbvlMxEM3gKVEvZuPEzUMVztwPJKmPJMsVO0JJRb2YKyst7oFWxLliwahsfHgxWCrDWYZDlaIsUt/lsueHqGzcpbY+MboduiPmve7K/o/bXtC+L9cVgMjnRb2kzT3b+1At+5J6bhdWgVG9JVpSTmP/PyhvVfWIfpys6mdQ9U1z8MSIxjmQFBIfDTNhaFkoZW58PQuHZ9GAjjJYuJHtTBTsy3SzzftX6D1OM+veL6DtzlG3obd6Y0AGfGfHdHkPAu/lGIBvbZ6WMtSmTEcUF2nRxmBWDolElgDhT8xdh85WaqilpVngN5wjxt5tGv+my8vBLEbU5qSXgT7R88F1uPINxsLpLxh8znpWh9S6t3/WIDRPii7wamRueQK0oAJnG5/YdDv58C5r3V7G1Uly9t/5uKXTmMEl3GrQ1vJiMg0VjjNE/57WMlnDHxyNydj8cf7BMUCufsQ6o/QnIH2W59ttZIp/0XXIIZp40MFpOM0lXiclDw2ldyUncvfHIH68hGyc56HsB/Eg="
  secret-access-key:
    secure: "j1QnsS01Rf+umK2ZbuQWbnaybFG0HdMh3LyIWtmtz6hzPSsklmxxG6vS/hXSv7utulh+pz5Ty4EP44i35Z+iF8/hPiQ8FKj0ZdRwHX9XzLu6+IAd55WtiPLCqH1epzeNn0JpZnJhiCZgsw30IEJkLtd5w8EAREQTMchDjDoX2wSIBl+sRzV804HbwxNUb8aXRoUB3fn9rkRhkPiR30jpzd/RUYZBFENi8e7GqR9MT6uQXJS0fL9qH2AQmt0/AYt1pganmu5DV/yivRZ6dCKzsW2R7F9KccVXndJTUSjUrzs1FJwcVwZk/omg0N8cSnu+RsiB+f6H4WyGZlPlF0b2vLqoWC1StRnEZiULZgLe7aHNSgc7CLkpjKnTGf3pX7N9IGLQQCZlzK7fOms+53wwNnMrTsWX3u4lCLl3Yv+FFGswVfhIo0TLTYGsDa6qGjvKXpjUmgaOEM8r9/zhghXVWMPE6dsq07rwuHPT5zcmkvM8fr0KyukSjhWxxFIu5GfSwMdyRnOzduV5TYMKd4RBkMb+HgrSqvanrZ+OxwtfKPi5A7DntN097FKcPKko61YdSjoAmIC00J2IV4yUHTzbVKTb4UwdiJVHBexDJAvG+eoILgwbwaL8ICZtc83R9AikeroBWwFuiK4UL/OEDWPRSyjObxuGleDrvau2XPccByQ="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "yvpjV1iG9/cC7P3+9P6z7trmBPDXFhQoqhblkzcXqDUwfzEZB9T6CE0EP0L/kUdlJMppzKue5nGBQ7w3YVuSyCmopdr5UtufYprG6VpQd8QzJMMY9H9U7LSpYhmxRxolTOFgmB3i7dnyY05IYHdBcQpcFBTVuSZunxbvlMxEM3gKVEvZuPEzUMVztwPJKmPJMsVO0JJRb2YKyst7oFWxLliwahsfHgxWCrDWYZDlaIsUt/lsueHqGzcpbY+MboduiPmve7K/o/bXtC+L9cVgMjnRb2kzT3b+1At+5J6bhdWgVG9JVpSTmP/PyhvVfWIfpys6mdQ9U1z8MSIxjmQFBIfDTNhaFkoZW58PQuHZ9GAjjJYuJHtTBTsy3SzzftX6D1OM+veL6DtzlG3obd6Y0AGfGfHdHkPAu/lGIBvbZ6WMtSmTEcUF2nRxmBWDolElgDhT8xdh85WaqilpVngN5wjxt5tGv+my8vBLEbU5qSXgT7R88F1uPINxsLpLxh8znpWh9S6t3/WIDRPii7wamRueQK0oAJnG5/YdDv58C5r3V7G1Uly9t/5uKXTmMEl3GrQ1vJiMg0VjjNE/57WMlnDHxyNydj8cf7BMUCufsQ6o/QnIH2W59ttZIp/0XXIIZp40MFpOM0lXiclDw2ldyUncvfHIH68hGyc56HsB/Eg="
  secret-access-key:
    secure: "j1QnsS01Rf+umK2ZbuQWbnaybFG0HdMh3LyIWtmtz6hzPSsklmxxG6vS/hXSv7utulh+pz5Ty4EP44i35Z+iF8/hPiQ8FKj0ZdRwHX9XzLu6+IAd55WtiPLCqH1epzeNn0JpZnJhiCZgsw30IEJkLtd5w8EAREQTMchDjDoX2wSIBl+sRzV804HbwxNUb8aXRoUB3fn9rkRhkPiR30jpzd/RUYZBFENi8e7GqR9MT6uQXJS0fL9qH2AQmt0/AYt1pganmu5DV/yivRZ6dCKzsW2R7F9KccVXndJTUSjUrzs1FJwcVwZk/omg0N8cSnu+RsiB+f6H4WyGZlPlF0b2vLqoWC1StRnEZiULZgLe7aHNSgc7CLkpjKnTGf3pX7N9IGLQQCZlzK7fOms+53wwNnMrTsWX3u4lCLl3Yv+FFGswVfhIo0TLTYGsDa6qGjvKXpjUmgaOEM8r9/zhghXVWMPE6dsq07rwuHPT5zcmkvM8fr0KyukSjhWxxFIu5GfSwMdyRnOzduV5TYMKd4RBkMb+HgrSqvanrZ+OxwtfKPi5A7DntN097FKcPKko61YdSjoAmIC00J2IV4yUHTzbVKTb4UwdiJVHBexDJAvG+eoILgwbwaL8ICZtc83R9AikeroBWwFuiK4UL/OEDWPRSyjObxuGleDrvau2XPccByQ="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-mt-worker
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
- provider: elasticbeanstalk
  edge: true
  access-key-id:
    secure: "yvpjV1iG9/cC7P3+9P6z7trmBPDXFhQoqhblkzcXqDUwfzEZB9T6CE0EP0L/kUdlJMppzKue5nGBQ7w3YVuSyCmopdr5UtufYprG6VpQd8QzJMMY9H9U7LSpYhmxRxolTOFgmB3i7dnyY05IYHdBcQpcFBTVuSZunxbvlMxEM3gKVEvZuPEzUMVztwPJKmPJMsVO0JJRb2YKyst7oFWxLliwahsfHgxWCrDWYZDlaIsUt/lsueHqGzcpbY+MboduiPmve7K/o/bXtC+L9cVgMjnRb2kzT3b+1At+5J6bhdWgVG9JVpSTmP/PyhvVfWIfpys6mdQ9U1z8MSIxjmQFBIfDTNhaFkoZW58PQuHZ9GAjjJYuJHtTBTsy3SzzftX6D1OM+veL6DtzlG3obd6Y0AGfGfHdHkPAu/lGIBvbZ6WMtSmTEcUF2nRxmBWDolElgDhT8xdh85WaqilpVngN5wjxt5tGv+my8vBLEbU5qSXgT7R88F1uPINxsLpLxh8znpWh9S6t3/WIDRPii7wamRueQK0oAJnG5/YdDv58C5r3V7G1Uly9t/5uKXTmMEl3GrQ1vJiMg0VjjNE/57WMlnDHxyNydj8cf7BMUCufsQ6o/QnIH2W59ttZIp/0XXIIZp40MFpOM0lXiclDw2ldyUncvfHIH68hGyc56HsB/Eg="
  secret-access-key:
    secure: "j1QnsS01Rf+umK2ZbuQWbnaybFG0HdMh3LyIWtmtz6hzPSsklmxxG6vS/hXSv7utulh+pz5Ty4EP44i35Z+iF8/hPiQ8FKj0ZdRwHX9XzLu6+IAd55WtiPLCqH1epzeNn0JpZnJhiCZgsw30IEJkLtd5w8EAREQTMchDjDoX2wSIBl+sRzV804HbwxNUb8aXRoUB3fn9rkRhkPiR30jpzd/RUYZBFENi8e7GqR9MT6uQXJS0fL9qH2AQmt0/AYt1pganmu5DV/yivRZ6dCKzsW2R7F9KccVXndJTUSjUrzs1FJwcVwZk/omg0N8cSnu+RsiB+f6H4WyGZlPlF0b2vLqoWC1StRnEZiULZgLe7aHNSgc7CLkpjKnTGf3pX7N9IGLQQCZlzK7fOms+53wwNnMrTsWX3u4lCLl3Yv+FFGswVfhIo0TLTYGsDa6qGjvKXpjUmgaOEM8r9/zhghXVWMPE6dsq07rwuHPT5zcmkvM8fr0KyukSjhWxxFIu5GfSwMdyRnOzduV5TYMKd4RBkMb+HgrSqvanrZ+OxwtfKPi5A7DntN097FKcPKko61YdSjoAmIC00J2IV4yUHTzbVKTb4UwdiJVHBexDJAvG+eoILgwbwaL8ICZtc83R9AikeroBWwFuiK4UL/OEDWPRSyjObxuGleDrvau2XPccByQ="
  region: ap-southeast-1
  app: twilreapi
  env: twilreapi-cdr-processor
  bucket_name: somlengci
  on:
    repo: dwilkie/twilreapi
    branch: app.somleng.org
