language: ruby
services:
  - postgresql
env:
  - START_SIMPLECOV=1
addons:
  postgresql: '9.4'
  code_climate:
    repo_token:
      secure: "uSDvlBKPuuQBX6exm2qWQCo5mjm0XmggJWc9NaqAkdkwKd8D7nKZBr7QwZ19bXHipqFIoWieMzPMD+9U6OxVmimhH8ADZyubDm6NJNxqrOX5Uy1rFfD1pIGocNYYPk/2wHu1H14Bx6J/7xm0ckKMmyA6YuqEskAXVCwKk2zGZJXAN2uambdvI/XLczssHHv72i6pflDkf1kc4zPlpjUaMA1ZuIsCibCh+WQ7W/jXXgutBSrKij8G0XRAv0GUYX/2p0hwKFtrvFBZ74JOjokdTykRwey85DnJIOhLmhbensge0E1/9f0hm7Z7mMNGNJwW11cuCHOExSkO+JBSRWmzYmqCj1jqJpBSFWpcv53ya8XglgcJ+BBOzgH5zqVe1LZ2hn6t5w++J5wpbxfG6SnzB3tYaBhpb1heP4KcnfOgfkUvivXbNQfYmKzjpZ6WJAfs4tTAnVhCq1e3Ipb3bHbo3tZcSKl2EcHBcatTSblam5a1aKxNzJT6c7DOH6VvjSE/KHTn0iLg+hPE09+NSHESz/psuL5dA21VN0CCL879SEf/7PyyPVwTcJO1bQf8zAM5ZdW7CnslIZ2HsuALcKNkVT2PjToeFGcrO/udy9li2Bx5gBFYnVCjO/2Agx0Kg1/JcfMauohCIqlPUlkp1fiJqjyWvLI56tKud21XwKZJeI0="
before_script:
  - psql -c 'create database twilreapi_test;' -U postgres
  - psql -U postgres -c "create extension pgcrypto"
deploy:
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-web
    bucket_name: pin-somlengci
    on:
      repo: dwilkie/twilreapi
      branch: somleng.ews1294.info
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-worker
    bucket_name: pin-somlengci
    on:
      repo: dwilkie/twilreapi
      branch: somleng.ews1294.info
  - provider: elasticbeanstalk
    edge: true
    access-key-id:
      secure: "04oV9WHvUkqi5SEsFg2HLWNx54gXAQjyRwW8CXgv6QELLjRRigzDGoYgpv0vggPEuwOQf7kabEFnv+p2GxpYmnvJZeW6FtpyNP2qLWHmcCto+GYqBJSw7bC5DzWF2CXLRFJjVQoHj2GI5ofEn0Mt72dWPiR6KaIzNhOpv39vELZ52+IdJ3TqhiD3lH9oOuOv1jgB37XRGvs5PeeIL1WS/bIVwfz12Q4K0D1kZXOegjHKVf7o+GP++EfrUys9BtDgNYkNzB76wArZS1kQZWuv6OBraMQpp+k0bj5E5p2hnjqPJnLVqxUEO7M8gD85tL5X2Bxmc2oRKVhgL7yZ0PRFKFIBXVq1YOSNfniRs710a7Y7Ts53k47okS5lYmkWsGDJTP/p4nLgekdfF11HXmkB6bJWfJO2grSYx4Rj5q/gAkpzSp2OlBpp0Uv+AjRAYXzZScYoEC/VEQAxFjs9Iknys6HXTp5xJregf2sfgQF6woTGncP6lWVb++DMIErDUaCm57A+3xGxnR+rP7EL+wcGj+DW4Y8wPCMWxDecf4PYLsAZwja9GZIOXLakyCS2gn9Ob9jClf903ZMjY11Rs0uH0phc7LNHGGyFnSf1rIR5dlu1pXFL/82EJBMp1eQx7zoFyAFRg8qTwJVYsV1nrcdSlLImkjyKBTmV/OjTtmIgpvc="
    secret-access-key:
      secure: "KPqgBcYUQrfxh5kff6Se1As6woZd+sKA9aXYFjTwQS4CnaF4UpteH7JAYo+xH0UoG8q0N4XwKCIL4z1rO4nFlWmfdDT93TCBA+EblWOi9h6lrHwc/KfpZ6xsVBp0wvK723L5kwhR3c+ypF2+P0qQAjHxPVfqAgaWpfX8Tu2vBMcD8mclLbpQA+yoPXfIA0K2szOTi8CN9IrotsUye+fKzlmylvMP1H0S/KkTOZsd40cIC803lnOuiezRQLWToEKMOZ/337OzpZ7do5Kn/qw0AE1dUCc/VJix9eT84IvFR4v4b/01CUvrUJuDSSWs2QcHE1QkDD/67TMRCQUsiknhw57ntYcQx9nJgcWSDOEs9WzshOsWN0T/mX41Zb74K6CBMr5Cc1WlknfeuYE/UUupJyR7AmgMudpT3pOrDCzY7plTgNrxojGRwqMvcId21+IEPim3u++jm7Nrg2IKBBbkUu4spbUsfRU31qfnGDcw7fb5scLtI0Rfj47LFP8GJVVCfbjzWO47+k2S6EaXZIATksFtZ5covkVfxdtFGgVbvNyWXeLBDLoBVuggfnypbkCllVDlj6MY3Q3sHjhs9h7g1wpk7iXFqbgyfjwvZO2OTKsOfySnhGMj5jEdwHZExXvvYBe8u8C619APis9Q14NdkEP74E5ZGG85czsdje6Bajk="
    region: ap-southeast-1
    app: twilreapi
    env: twilreapi-cdr-processor
    bucket_name: pin-somlengci
    on:
      repo: dwilkie/twilreapi
      branch: somleng.ews1294.info
after_success:
  - bundle exec codeclimate-test-reporter
